[package]
categories = ["cryptography", "zk", "blockchain", "ceno"]
description = "Ceno zkVM Crypto Guest Library"
edition = "2021"
keywords = ["cryptography", "zk", "blockchain", "ceno"]
license = "MIT OR Apache-2.0"
name = "ceno_crypto"
readme = "README.md"
repository = "https://github.com/scroll-tech/ceno"
version = "0.1.0"

[dependencies]
bn = { package = "substrate-bn", git = "https://github.com/scroll-tech/bn", branch = "ceno" }
ceno_keccak = { path = "../keccak" }
ceno_sha2 = { path = "../sha2" }
k256 = { git = "https://github.com/hero78119/elliptic-curves", rev = "e4b858da2aabbb81668356b46e1b2b72bb6aeeed", default-features = false, features = ["std", "ecdsa"] }
thiserror.workspace = true

[dev-dependencies]
alloy-consensus = { version = "1.0", features = ["crypto-backend"] }
alloy-primitives = "1.4"
revm-precompile = "27"
