[package]
categories.workspace = true
description = "Macros for the Ceno project"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "sumcheck_macro"
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
itertools.workspace = true
p3 = { path = "../p3" }
proc-macro2 = "1.0.92"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
ff_ext = { path = "../ff_ext" }
multilinear_extensions = { path = "../multilinear_extensions" }
sumcheck = { path = "../sumcheck" }
