[target.riscv32im-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tmemory.x", "-C", "link-arg=-Tceno_link.x"]

[build]
target = "riscv32im-unknown-none-elf"

[profile.dev]
panic = "abort"
lto = "thin"

[profile.release]
lto = true
panic = "abort"
